[project]
name = "db-migrations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic==1.15.2",
    "alembic-postgresql-enum==1.7.0",
    "core",
    "db",
    "dotenv>==0.9.9",
    "sqlalchemy==2.0.44",
]
