[project]
name = "db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["core", "sqlalchemy==2.0.44"]

[build-system]
requires = ["uv_build>=0.9.21,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
core = { workspace = true }

[tool.ruff]
extend = "../../pyproject.toml"

[tool.ruff.lint]
ignore = ["RUF012"]
