[project]
name = "infini-gram-api-client"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["attrs>=21.3.0", "httpx~=0.28.0"]

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
